FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Install uvicorn
RUN pip install uvicorn

# Copy your application code
COPY ./API/venv/message.py /app/message.py
COPY ./requirements.txt /app/requirements.txt

# Set the working directory
WORKDIR /app

# Expose the necessary port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "message:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
