version: '3.8'

services:
  
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name:  portfolio-app

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./message.py:/app/message.py
    ports:
      - "8000:80"
   
   
      
