version: '3.8'

services:

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name: portfolio-app
    networks:
      - my_network

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    container_name: portfolio-api
    networks:
      - my_network

  apache-server:
    image: httpd:2.4.55
    container_name: apache-server
    volumes:
      - /etc/apache2/sites-available/000-default.conf:/usr/local/apache2/conf/sites-available/000-default.conf
      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
    ports:
      - "443:443"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge








# version: '3.8'

# services:

#   angular-app:
#     build:
#       context: ./
#       dockerfile: dockerfile
#     restart: always
#     volumes:
#       - ./configurations/Client/docker-proxy:/etc/nginx/sites-available/docker-proxy
#     ports:
#       - "8080:80"
#       - "8081:443"
#     container_name: portfolio-app
#     networks:
#       - my_network

#   fastapi-app:
#     image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
#     volumes:
#       - ./configurations/API/docker-proxy:/etc/nginx/sites-available/docker-proxy
#       - ./API/venv/message.py:/app/message.py
#       - ./requirements.txt:/app/requirements.txt
     
#     command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
#     ports:
#       - "8000:8080"
#       - "8001:8081"
#     container_name: portfolio-api
#     networks:
#       - my_network
# networks:
#   my_network:


  # nginx-proxy:
  #   image: nginx:latest
  #   ports:
  #     - "81:80"
  #     - "433:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
  #   depends_on:
  #     - angular-app
  #     - fastapi-app
  #   container_name: portfolio-proxy


