version: '3.8'

services:
  
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"  # Use a different host port, e.g., 8080
    container_name: portfolio-app
  
  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn message:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:80"  # Use a different host port, e.g., 8000
    container_name: portfolio-api
