version: '3.8'

services:
  # proxy-server:
  #   image: nginx:latest
  #   volumes:
  #     - /etc/nginx/:/etc/nginx/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - angular-app
  #     - fastapi-app

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
      - "8080:443"
    container_name: portfolio-app

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:80"
      - "8000:443"
    container_name: portfolio-api

