version: '3.8'

services:
  
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name:  portfolio-app
    networks:
      - mynetwork
    

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./message.py:/app/message.py
    container_name:  portfolio-api
    networks:
      - mynetwork
    ports:
      - "8000:80"
      
networks:
  mynetwork:
      
