version: '3.8'

services:

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    container_name: portfolio-app
    networks:
      - my_network

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:

      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
     
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    container_name: portfolio-api
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
       - ./cert/:/etc/cert/
    ports:
      - "80:80"
      - "8443:443"
    container_name: portfolio-nginx
    networks:
      - my_network
  
networks:
  my_network:


  # nginx-proxy:
  #   image: nginx:latest
  #   ports:
  #     - "81:80"
  #     - "433:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
  #   depends_on:
  #     - angular-app
  #     - fastapi-app
  #   container_name: portfolio-proxy


