version: '3.8'

services:
  apache-server:
    image: httpd:latest
    ports:
      - "80:80"
    # Other Apache configurations, if needed

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name: portfolio-app

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    container_name: portfolio-api
