version: '3.8'

services:
  
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"  # Use a different host port, e.g., 8080
    container_name: portfolio-app
  
  fastapi-app:
    build:
      context: ./
      dockerfile: dockerfile-p  # Point to the Dockerfile for FastAPI
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"  # Use a different host port, e.g., 8000
    container_name: portfolio-api
