version: '3'

services:
  certbot:
    restart: always
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email wward246@gmail.com -d williamjwardiii.com
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    container_name: certbot

     
    networks:
      - my_network
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount Let's Encrypt certificates
    container_name: portfolio-server
    networks:
      - my_network
    depends_on:
      - certbot  # Make sure Certbot runs before the webserver

  angular-app:    
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:8080"
    container_name: portfolio-app
    networks:
      - my_network

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    container_name: portfolio-api
    networks:
      - my_network



networks:
  my_network:



# version: '3.8'

# services:

#   angular-app:
    
#     build:
#       context: ./
#       dockerfile: dockerfile
#     restart: always
#     volumes:
#       - /etc/letsencrypt/live/williamjwardiii.com/:/etc/cert/ssl/
#       - ./configurations/Client/docker-proxy:/etc/nginx/sites-available/docker-proxy
    
#     ports:
#       - "8080:80"
#       - "8081:443"
#     container_name: portfolio-app
#     networks:
#       - my_network

#   fastapi-app:
#     image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
#     volumes:
#       - /etc/letsencrypt/live/williamjwardiii.com/:/etc/cert/ssl/
#       - ./configurations/API/docker-proxy:/etc/nginx/sites-available/docker-proxy
#       - ./API/venv/message.py:/app/message.py
#       - ./requirements.txt:/app/requirements.txt
      
      
#     command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
#     ports:
#       - "8000:8000"
#       - "8001:443"
#     container_name: portfolio-api
#     networks:
#       - my_network

#   # nginx-proxy:
#   #   image: nginx:latest
#   #   ports:
#   #     - "81:80"
#   #     - "433:443"
#   #   volumes:
#   #     - ./nginx.conf:/etc/nginx/nginx.conf
#   #      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
#   #   depends_on:
#   #     - angular-app
#   #     - fastapi-app
#   #   container_name: portfolio-proxy

# networks:
#   my_network: