version: '3.8'

services:
  # apache-server:
  #   image: httpd:latest
  #   ports:
  #     - "8080:80"
  #   # Other Apache configurations, if needed
  #   networks:
  #   - mynetwork

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8081:80"
      - "8081:443"
    container_name: portfolio-app
   

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:80"
      - "8000:443"
    container_name: portfolio-api
    
  # nginx-server:
  #   image: nginx:latest
  #   volumes:
  #     - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "8082:80"
  #   depends_on:
  #     - apache-server
  #     - angular-app
  #     - fastapi-app
  # container_name: portfolio-nginx
