version: '3.8'

services:

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:81"
    container_name: portfolio-app

  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./API/venv/message.py:/app/message.py
      - ./requirements.txt:/app/requirements.txt
      - /etc/letsencrypt/live/williamjwardiii.com/:/etc/letsencrypt/live/williamjwardiii.com/
    command: bash -c "python3 -m uvicorn message:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    container_name: portfolio-api

  nginx-proxy:
    image: nginx:latest
    ports:
      - "81:80"
      - "433:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - angular-app
      - fastapi-app
