version: '3.8'

services:
  
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name:  portfolio-app
    networks:
      - mynetwork
    

  fastapi-app:
    build:
      context: ./
      dockerfile: dockerfile-p
      container_name:  portfolio-api
      networks:
       - mynetwork
    ports:
      - "8000:8000"
      
networks:
  mynetwork:
      
